### PR TITLE
middleware: Separate close and finish events

### PR DESCRIPTION
**Pull request by meschbach**
This cleans up the logging on newer NodeJS versions where `finish` is the intent to drain and close, while `close` represents the actual destruction of the underlying resources.

### CODE REVIEW

**Comment by meschbach** [comment]
This would resolve #16 too.

**Comment by sam-burrell** [comment]
is there anything blocking this merge currently?

**Comment by obscurerichard** [comment]
I ran into this issue while testing this library as part of the work I'm doing in writing a book - I'd love it if this got resolved because #16 is a big annoyance.

Can someone help evaluate and merge this please @rnburn @rgarcia @drhurd ?

**Comment by drhurd** [comment]
cc @austinlparker @iredelmeier

**Comment by austinlparker** [comment]
Lemme figure out who has the creds to release this, but yeah, we can get it out

**Pull request merged**
